export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const SAVE_LOGIN_DETAILS = 'SAVE_LOGIN_DETAILS'
export const GET_LOGIN = 'GET_LOGIN';
